### ISSUE TITLE
loadMasketWallet error

### ISSUE THREAD

**Issue by andrewAIS** [togetair/cordova-android-pay#1]
When I follow the code for setup until the following code
.then(function(result) {
  console.log(result);
  return AndroidPay.loadMasketWallet();
})

It throws the following error
AndroidPay.loadMasketWallet is not a function

In addition, 
May I know how to" send to server" if I am using stripe?

 .then(function(tokenizationResult) {
  console.log(tokenizationResult);

  // send to server
})

**Comment by uwgmk** [comment]
@andrewAIS Nice catch, it should be `AndroidPay.loadMaskedWallet` and not maske**t**.

**Comment by uwgmk** [comment]
As for the *send to server* part, you will receive the tokenization result (just like if you were using stripe elements) and need to do the actual processing, which must be done server-side.

Refer to Stripe's documentation: https://stripe.com/docs/charges
